repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.2
    hooks:
      - id: gitleaks

  - repo: https://github.com/avito-tech/deepsecrets
    rev: v1.1.3
    hooks:
      - id: deepsecrets
