- name: Get current directory
  ansible.builtin.shell:
    cmd: cd ../ ; pwd
  register: current_dir

- name: Set repo directory path
  set_fact:
    repo_path: "{{ current_dir.stdout }}"

- name: Install pre-commit on Debian/Ubuntu
  become: yes
  apt:
    name: pre-commit
    state: present
  when: ansible_os_family == "Debian"

- name: Install pre-commit on CentOS
  become: yes
  yum:
    name: pre-commit
    state: present
  when: ansible_os_family == "RedHat"

- name: Install pre-commit on macOS
  command: brew install pre-commit
  when: ansible_system == "Darwin"

- name: Install pre-commit hooks
  command: pre-commit install
  args:
    chdir: "{{ repo_path }}"

- name: Create .pre-commit-hooks.yaml
  copy:
    content: |
      repos:
        - repo: https://github.com/gitleaks/gitleaks
          rev: v8.18.1
          hooks:
            - id: gitleaks

        - repo: https://github.com/avito-tech/deepsecrets
          rev: v1.1.2
          hooks:
            - id: deepsecrets
    dest: "{{ repo_path }}/.pre-commit-hooks.yaml"

- name: Auto-update pre-commit hooks
  command: pre-commit autoupdate -c "{{ repo_path }}/.pre-commit-hooks.yaml" --no-verify
  args:
    chdir: "{{ repo_path }}"
