# - name: Install Gitleaks
#   command: go install github.com/zricethezav/gitleaks@latest
#   args:
#     creates: ~/go/bin/gitleaks

- name: Clone gitleaks repository
  git:
    repo: https://github.com/gitleaks/gitleaks.git
    dest: "{{ repo_path }}/gitleaks"

- name: Build gitleaks
  shell: make build
  args:
    chdir: "{{ repo_path }}/gitleaks"

- name: Create venv for Deepsecrets
  command: python3.12 -m venv "{{ repo_path }}/.venv"
  

- name: Install Deepsecrets
  pip:
    requirements: "{{ repo_path }}/ansible_pipeline/requirements.txt"
    virtualenv: "{{ repo_path }}/.venv"
 

- name: Check for secrets using Deepsecrets
  command: "{{ repo_path }}/.venv/bin/deepsecrets --target-dir {{ repo_path }}/src --outfile {{ repo_path }}/ds-result.json" 
  ignore_errors: true
  register: deepsecrets_output

- name: Check for secrets using Gitleaks
  command: "{{ repo_path }}/gitleaks/gitleaks detect --source {{ repo_path }} -f json --report-path {{ repo_path }}/gl-result.json"
  ignore_errors: true
  register: gitleaks_output



- name: Fail if secrets are found
  # fail:
  debug:
    msg: "Secrets found in the code"
  when: gitleaks_output.rc != 0 or deepsecrets_output.rc != 0

