- name: Install Gitleaks
  command: go install github.com/zricethezav/gitleaks@latest
  args:
    creates: ~/go/bin/gitleaks
  when: ansible_system == "Darwin"

- name: Create venv for Deepsecrets
  command: python3.12 -m venv "{{ repo_path }}/.venv"
  when: ansible_system == "Darwin"

- name: Install Deepsecrets
  pip:
    requirements: "{{ repo_path }}/ansible_pipeline/requirements.txt"
    virtualenv: "{{ repo_path }}/.venv"
  when: ansible_system == "Darwin"

- name: Check for secrets using Deepsecrets
  command: "{{ repo_path }}/.venv/bin/deepsecrets --target-dir {{ repo_path }} --outfile {{ repo_path }}/ds-result.json" 
  ignore_errors: true
  register: deepsecrets_output

- name: Check for secrets using Gitleaks
  command: "~/go/bin/gitleaks --repo-path {{ repo_path }} --report {{ repo_path }}/gl-result.json"
  ignore_errors: true
  register: gitleaks_output

- name: Fail if secrets are found
  # fail:
  debug:
    msg: "Secrets found in the code"
  when: gitleaks_output.rc != 0 or deepsecrets_output.rc != 0

