---
- name: Pull DefectDojo Docker image
  docker_image:
    source: pull
    name: "defectdojo/defectdojo-django:2.0.2"
    state: present


- name: Create directory for DefectDojo data
  file:
    path: "{{ repo_path }}/defectdojo"
    state: directory

- name: Run DefectDojo Docker container
  docker_container:
    name: defectdojo
    image: defectdojo/defectdojo-django:2.0.2
    state: started
    restart_policy: always
    ports:
      - "8080:8080"
    volumes:
      - "{{ repo_path }}/defectdojo:/opt/django-DefectDojo"
